#!/usr/bin/env python3
import xml.etree.ElementTree as et
import sys

try:
    xml = sys.argv[1]
except(IndexError):
    print('Usage: num_dropped_levels logfile')
    exit(1)

root = et.parse(xml).getroot()
analyze_metric = next(root.iter('AnalyzeMetric'))
num_ops = int(analyze_metric.find('NumberOfOperators').text)
num_retained = int(analyze_metric.find('MetricRank').text)

print(num_ops - num_retained)

