#!/usr/bin/env python
import sys
from xml.etree import ElementTree as et

try:
    filename = sys.argv[1]
except:
    sys.exit('Usage: resamplings_from_log logfile (optional: output_directory)')

output_dir = sys.argv[2] if len(sys.argv) > 2 else ''
if bool(output_dir):
    if output_dir[-1] != '/':
        output_dir += '/'

tree = et.parse(filename)
root = tree.getroot()
tasks = root.findall('Task')
PrintXML_elements = [task.find('PrintXML') for task in tasks if len(task.findall('PrintXML'))]
resampling_mode = 'Bootstrap' if bool(PrintXML_elements[0].findall('Bootstrap')) else 'Jackknife'
for PrintXML in PrintXML_elements:
    MCO = PrintXML.find('MCObservable').find('Info').text
    sample_avg = PrintXML.find('MCEstimate').find('FullEstimate').text
    resamplings = [resampling_element.find('Value').text for resampling_element in PrintXML.findall(resampling_mode)]
    file_out = open(output_dir + MCO + 'resamplings.dat','w')
    lines = [sample_avg]+resamplings
    file_out.writelines(line + '\n' for line in lines)
    file_out.close()
